### ISSUE TITLE
Use `motor` instead of `pymongo`

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#1]
The initial implementation of `api.db` is based on `pymongo` to access the Mongo DB instance.  While this works fine, an alternative would be to use [`motor`](https://motor.readthedocs.io/en/stable/) which provides support for asynchronous queries.  This should help from a performance standpoint.

Here's an interesting Gist about migrating from `pymongo` to `motor`:
https://gist.github.com/anand2312/840aeb3e98c3d7dbb3db8b757c1a7ace

Steps:
- [ ] Follow the README to get an instance up and running with a user account
- [ ] Run some queries using `curl` to create and retrieve Thing objects
- [ ] Update `requirements.txt` to install `motor`
- [ ] Update the `api.db` implementation to rely on `motor`
- [ ] Run the same queries to create and retrieve Thing objects and check it's still working (as we don't have unit tests yet)
- [ ] Update `api.main` with the `async` keyword as appropriate
- [ ] Update `requirements.txt` to drop `pymongo`

Then create the following commits on a branch:
1. add `motor` to requirements
2. update `api.db` to use `motor`
3. use `async` in `api.main` where it's missing
4. drop `pymongo` from `requirements.txt`

Push this branch to a fork of `kernelci-api` and create a pull request.

**Comment by mharyam** [comment]
Hello @gctucker , 

I am trying to work on this but I am having some issues 

So I updated the find_one function in db.py to : 

>     async def find_one(self, model, **kwargs):
>         col = self._get_collection(model)
>         return await model(col.find_one(kwargs))
> 

When trying to authorize with the authenticate_user function 

>     def authenticate_user(self, username: str, password: str):
>         user =  self._db.find_one(User, username=username)
>         if not user:
>             return False
>         if not self._pwd_context.verify(password, user.hashed_password):
>             return False
>         return user
> 

I got an error 

> AttributeError: 'coroutine' object has no attribute 'hashed_password'

I notice this is happening because the function for getting user is retuning <coroutine object Database.find_one at 0x7fe6205faec0> a coroutine object 

How can I get the obj User from this coroutine object?

**Comment by gctucker** [comment]
This is because some code is being called asynchronously without being defined in an `async` function.  As the current `api.db` implementation is synchronous, the issue doesn't appear.  But I believe you'll need this fix:
```diff
diff --git a/api/auth.py b/api/auth.py
index 065ffa6124a2..b58bc3d5039f 100644
--- a/api/auth.py
+++ b/api/auth.py
@@ -39,8 +39,8 @@ class Authentication:
     def get_password_hash(self, password):
         return self._pwd_context.hash(password)
 
-    def authenticate_user(self, username: str, password: str):
-        user = self._db.find_one(User, username=username)
+    async def authenticate_user(self, username: str, password: str):
+        user = await self._db.find_one(User, username=username)
         if not user:
             return False
         if not self._pwd_context.verify(password, user.hashed_password):
@@ -57,7 +57,7 @@ class Authentication:
             to_encode, self.SECRET_KEY, algorithm=self.ALGORITHM)
         return encoded_jwt
 
-    def get_current_user(self, token):
+    async def get_current_user(self, token):
         try:
             payload = jwt.decode(
                 token, self.SECRET_KEY, algorithms=[self.ALGORITHM])
@@ -68,4 +68,4 @@ class Authentication:
         except JWTError:
             return None
 
-        return self._db.find_one(User, username=token_data.username)
+        return await self._db.find_one(User, username=token_data.username)
diff --git a/api/main.py b/api/main.py
index fa5e24cc32b9..5949aecb36b9 100644
--- a/api/main.py
+++ b/api/main.py
@@ -16,7 +16,7 @@ auth = Authentication(db)
 
 
 async def get_current_user(token: str = Depends(oauth2_scheme)):
-    user = auth.get_current_user(token)
+    user = await auth.get_current_user(token)
     if user is None:
         raise HTTPException(
             status_code=status.HTTP_401_UNAUTHORIZED,
```
as well as adding `async` to all the methods in `api.db` that use `motor` to communicate with the database.  For example:
```python
    async def find_one(self, model, **kwargs):
```

**Comment by mharyam** [comment]
Thank you @gctucker  for the guide.

I have created a pull request to close this.
