### ISSUE TITLE
Load all `api.auth` parameters from Settings

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#10]
Now that we have a Settings object to load parameters from the environment, we can add `ALGORITHM` and `ACCESS_TOKEN_EXPIRE_MINUTES` to it as well.  The `ALGORITHM` setting should have a default value of `HS256`, and the token timeout should have a default to `None` so the tokens don't expire.  The secret key is required and it can't have a default value as it needs to be unique with each instance.

Steps:
* Set up a local instance following the instructions in the README
* Create a user and make sure login works
* Update `api/auth.py` to load the settings from the environment with default values as per the description above
* Check that the user can still login
* Set a token timeout to 1 minute in the environment file and restart docker-compose
* Check that the user can still login, and that the token has expired after 1 minute (queries should start returning HTTP 404)
  See also the FastAPI documentation about JWT tokens: https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/

Then create a branch with 2 commits:
1. Code in `api/auth.py`
  * Move `ALGORITHM` and `ACCESS_TOKEN_EXPIRE_MINUTES` to the Settings class with default values
  * Update the code in the Authentication class to use the values from the `self._settings` object
2. Documentation and sample environment file
* Add the ` ACCESS_TOKEN_EXPIRE_MINUTES` and `ALGORITHM` variables to `env.sample` but commented-out, in case the user wants to override them
* Add a mention in the README file about these settings

Push this branch to a fork of `kernelci-api` and create a pull request.

**Comment by JenySadadia** [comment]
@gctucker Claimed.
