### ISSUE TITLE
Expose staging API services

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#117]
Now that a KernelCI API and pipeline instances are being deployed on staging.kernelci.org, the ports for storage, SSH and API need to be exposed.

Here's a suggestion to get started, until sub-domains are created using ports in the 9000-9999 range:
* KernelCI API: https://api.staging.kernelci.org:9000 with Let's Encrypt cert and host Nginx server proxy for API container
* Storage: http://storage.kernelci.org:9080 without SSL initially to keep the config simple, host Nginx server proxy for storage container
* SSH: port 9022 direct access to the SSH container

**Comment by gctucker** [comment]
@mgalka I've configured the ports as defined above using these environment variables:
```
API_HOST_PORT=9000
STORAGE_HOST_PORT=9080
SSH_HOST_PORT=9022
```

I've also opened them in the Azure firewall so they should all be available already.

I've verified that SSH worked over port 9022, after adding my key to the container:
```
$ ssh -i id_rsa_kernelci-api -p 9022 kernelci@staging.kernelci.org
Linux f09ce0affc6e 5.10.0-10-cloud-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64
```

Also plain HTTP just works with the Nginx container serving files directly so I think we can leave that as-is for now.  If we want to add SSL support then we probably should go through the other Nginx instance running on the host, or a dedicated proxy such as HAProxy. But I think that's for a bit later.

Here's a quick way to verify it works:
```
$ curl http://staging.kernelci.org:9080/README.txt
This is the storage Server of the KernelCI-API docker environment.
```

The storage URL in the kernelci-pipeline environment file for the containers running on staging has been updated to use this base URL as well.

The last part is to enable SSL on the main API port.  At the moment it can be accessed directly, like the storage:
```
$ curl http://staging.kernelci.org:9000
{"message":"KernelCI API"}
```
I'm not trying it with an API token since it's not encrypted yet. I guess we may need to change the port exposed by the container so that Nginx can then proxy to it with the 9000 public port.  This can be done easily in the environment file as described at the top of this comment.

**Comment by mgalka** [comment]
I updated the proxy configuration so the API is available only over HTTPS, not encrypted connections over HTTP will end up with `HTTP 400`.
Application container is now available only through the proxy.

```
$ curl https://staging.kernelci.org:9000
{"message":"KernelCI API"}
```

```
$ curl http://staging.kernelci.org:9000
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
```
