### ISSUE TITLE
Add utility for creating user accounts

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#129]
The current approach for creating user accounts is to use the `/hash` API entry point to get a password hash, which means the password will appear in clear text in the API logs so that's not great.  Then the user has to be inserted manually into the Mongo DB which isn't great either.  Adding an "admin" account with permissions to create users is one possibility, although it means adding support for per-user permissions.  We will probably need to implement this soon anyway so that might just be the best way to do it.  Then we could have a `POST` request to an endpoint to create a user.

**Comment by JenySadadia** [comment]
All the related PRs have been merged.
Closing the issue.

**Comment by gctucker** [comment]
Could you please list the related PRs either in the description or link them in the "Development" section?

**Comment by JenySadadia** [comment]
Below is the list of related PRs:

- https://github.com/kernelci/kernelci-api/pull/140
- https://github.com/kernelci/kernelci-api/pull/141
- https://github.com/kernelci/kernelci-api/pull/143
- https://github.com/kernelci/kernelci-api/pull/144
