### ISSUE TITLE
Add nginx container for storage

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#15]
As described on #9, we need a file storage solution with an HTTP server to be able to store their URLs in the database.

The simplest approach is to add a container to [`docker-compose.yaml`](https://github.com/kernelci/kernelci-api/blob/main/docker/docker-compose.yaml) based on `nginx`:
https://hub.docker.com/_/nginx

Steps:
* Add `storage` section to `docker-compose.yaml` using latest stable `nginx` Docker image
* Define volume to be mounted in the standard path `usr/share/nginx/html` in the container, from a local directory in `storage/data` (just like `db/data` and `redis/data`).
* Expose port 80 from the container to 8002 on the host
* Add `storage/data/README.txt` file with a paragraph explaining this is the storage server.  It will also be useful to check the server is working.
* Run `docker-compose up --build` and try to access the README.txt file with `curl http://localhost:8002/README.txt`

Then on a branch from a fork of `kernelci-api`, create a Git commit with the changes in `docker-compose.yaml` and the new `README.txt` file.  Push the branch to create a pull request.

**Comment by gctucker** [comment]
@BitWire I've invited you to join the Hackers team so the issue can be assigned to you.

**Comment by gctucker** [comment]
@bitwire (and other Outreachy applicants) Please feel free to join the `#kernelci` IRC channel on libera.chat, and the kernelci@groups.io mailing list.  There's also a Slack chat on kernelci.slack.com, but that works on invitations only so please provide an email address if you would like to join.  Most other Outreachy applicants are already on Slack, it's a great way of keeping everyone on the same page.

**Comment by BitWire** [comment]
Alright 👍 will provide a mail Adress soon 😄

**Comment by BitWire** [comment]
@gctucker use thomas.schmidt@gastfreund.net for slack please

**Comment by gctucker** [comment]
> @gctucker use [thomas.schmidt@gastfreund.net](mailto:thomas.schmidt@gastfreund.net) for slack please

Thanks, invite sent.

**Comment by gctucker** [comment]
Resolving now that #17 has been merged.
