### ISSUE TITLE
Introduce End-to-End testing of kernelci-api

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-api#199]
An enviroment for running End-to-End tests of kernelci-api needs to be created.

End-to-End tests are needed to keep kernelci-api operational and detect failures in a timely manner. Apart from unit tests the project should also have a set of End-to-End tests. 
These tests should setup and run api server as well as a database with pre-populated set of data for each run. After the test runtime environment should be disposed.

- [ ] Create scripts to run testing environment
- [ ] Populate testing environment database with predefined data
- [ ] Run simple test case
- [ ] Prepare scripts to dispose the testing environment

**Comment by gctucker** [comment]
Side note: we might be able to run this in Azure pipeline from GitHub actions.  See for example the actions run by U-Boot PRs:
https://github.com/u-boot/u-boot/pulls

as defined in this file (moar YAML):
https://github.com/u-boot/u-boot/blob/master/.azure-pipelines.yml

**Comment by JenySadadia** [comment]
Here is the proposed solution for introducing E2E tests:
- Add a step for building and running docker services (`docker-compose up --build`) in Github Actions
- Create a script(shell/python) to connect to Database and create a test database (maybe `test_db`)
- Insert test data to the database from the script
- Add a step to Github actions to run the script for DB connection after services are up and running
- Add step/job to run tests in Github Actions
          - We may have separate `yml` files for each test case
          - Python `requests` package can be used to call API endpoints
          - I am not considering using any test framework (Selenium or Jmeter) at the moment
 - Dispose of the test database and disconnect the DB service from the script

**Comment by gctucker** [comment]
> Dispose of the test database and disconnect the DB service from the script

I guess this will be dealt with almost entirely automatically as the GitHub action environment will be garbage-collected just like the Python object holding a connection to the API or database.  But yes, it's a good idea to try and clean things up at the end of the check for completeness.

**Comment by gctucker** [comment]
Based on recent discussions, I think this can be split into tests that only involve `kernelci-api` with some specific client-side service to exercise the API without involving `kernelci-pipeline`.  That way, we can test the API itself in a self-contained way and even only rely on a single `docker-compose` instance to simplify things e.g. networking.

Then some tests based on `kernelci-pipeline` could be using the API instance on staging, but that might be a bit more complex to set up as it's adding an external dependency with an API token and the possibility that the API won't always be available.  It will be good to have tests to verify that things like timeout service is behaving as expected though.  It looks more like a higher level of functionality once we have the base API covered.  Probably this should be revisited once the API-centric tests are all set up and stable.

**Comment by JenySadadia** [comment]
> > Dispose of the test database and disconnect the DB service from the script
> 
> I guess this will be dealt with almost entirely automatically as the GitHub action environment will be garbage-collected just like the Python object holding a connection to the API or database. But yes, it's a good idea to try and clean things up at the end of the check for completeness.

Yes, I am running `docker-compose down` at the end to make sure the clean up.
