### ISSUE TITLE
Enable passing null as a request parameter for node parent

### ISSUE THREAD

**Issue by alexandrasp** [kernelci/kernelci-api#205]
After the experimental work to connect the API to the old dashboard, it could be interesting to provide a way to filter by the root parent in case the parent reference is NULL. I just got all nodes in time-filtered, using `gte` feature, and on the front-end side, I filter considering parent information to show jobs by branch, tree and kernel version.

**Comment by JenySadadia** [comment]
Yes, we can enable passing "null" as a request parameter value if it helps to reduce post-processing on the front-end side.
In fact, it should be implemented for all `Node` fields and not just for `parent`.

**Comment by gctucker** [comment]
I think the title of this issue should be changed as it's not very descriptive of what it's really about.

**Comment by alexandrasp** [comment]
I updated the title of the issue.
