### ISSUE TITLE
Add user ownership to nodes

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#256]
The new API allows more flexibility and any user with a token should be able to post results.  However, to be able to distinguish the results coming from the main KernelCI pipeline and for users to be able to find their own data, it would seem necessary to introduce the concept of nodes ownership.  Each node already has a creation date, we could add a field with the ID of the user who created it.  Then we could have simple rules such as only this user could update the node document, but others could refer to it e.g. to add child nodes.  We might need to add groups as a follow-up, for example all the runtimes orchestrated by the main pipeline could have users in some main KernelCI group and that could be used to sort results.  Also it could be a way for multiple users in a single organisation to submit data and update each others' nodes.

Before writing custom code for this, it would seem worth investigating existing frameworks.  We're already using JWT tokens which contain scopes and the OAuth2 standard for user authentication, and FastAPI has a security module with tools for this.  It would seem very simple to just add a user ID and add checks whenever a node is being updated whether the request was sent by the same user if we wanted to get started quickly.  But if we can directly adopt an existing framework with potentially some standard features to make the new API easier to use with other services.  There's a [StackOverflow discussion](https://stackoverflow.com/questions/58864648/oauth-2-0-flow-for-user-groups-organizations) about this among other things, it mentions LDAP so that could potentially be a way forward.

- [ ] `UserGroup` model implemented
- [ ] Logic in place to have users belong to groups
  - [x] #283

**Comment by JenySadadia** [comment]
As per my investigation, `FastAPI` doesn't have any plugin/tool or package to serve this purpose.
Some packages like https://pypi.org/project/fastapi_permissions/ and https://github.com/fastapi-users/fastapi-users provide utilities for user creation but we already have it in place with `OAuth2`. So I don't think any of them will be useful in this case.
`FastAPI` doesn't have any integration for LDAP as well. Maybe this can be used if we want to integrate LDAP operations manually https://www.python-ldap.org/en/python-ldap-3.3.0/.

Bdw this can be done using `scopes` from `OAuth2` scheme:
We can create a model `group` with `name` and `id` fields.
We will have two default groups `users` and `admin` group.
By default, user accounts with `admin` scope will be added to `admin` group, and `users` scope will be added to `users` group. `Node` will have two additional fields. One is the user ID of the user that created the node and another is the group ID that the user belongs to. When we receive `PUT` node request, we can check if it's the same user that created the object and if so we can grant permission for the requested action.
If not, we can check the group ID of requesting user and see if the user belongs to the same group as the user that created the object and grants the permission accordingly.

**Comment by JenySadadia** [comment]
Found more packages:
- https://pypi.org/project/easy-auth/
- https://github.com/amisadmin/fastapi-user-auth
