### ISSUE TITLE
Ensure groups aren't duplicated in User.groups list

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#283]
The `User.groups` field is a list, so there's no Python constraint to ensure there aren't any duplicates inside it.  Using a `Set[UserGroup]` is not really an option as a User object can't be hashed.  So there should be some logic instead in the model (or somewhere at the API application level) to enforce that groups are at most once in the `groups` list.

**Comment by JenySadadia** [comment]
We can use a constrained list from Pydantic. Please look at https://docs.pydantic.dev/latest/usage/types/#arguments-to-conlist

```
groups: conlist(UserGroup, unique_items=True)
```
