### ISSUE TITLE
Add docker-compose parameters for port numbers

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#29]
The port numbers exposed from containers to the host are currently hard-coded in `docker-compose.yaml`.  For example:
```yaml
    ports:
      - '8001:8000'
```
It would help to have the host port configurable with a docker-compose variable, instead of `8001` in the example above.  This would be required in order to avoid conflicts with other services already running on the host.

- [ ] variable added to `docker-compose.yaml`
- [ ] documentation updated accordingly

**Comment by himanshu007-creator** [comment]
Hi i would like to work on this issue
> My  Approach:

*create a variable as  <code>ARG HOST = 8001</code> and replace the above line with
<pre>
    ports:
      - '${HOST}:8000'
</pre>
If this is wrong, please correct me. I would be happy to make a PR for this one.

**Comment by gctucker** [comment]
Hi @himanshu007-creator, thank you for your interest.  I think this is technically the correct approach but we would need to make the variable names include the service, as other ports for new services would also need a parameter (ssh, nginx for file storage).  In this case, maybe something like `API_HOST_PORT` would remove any ambiguity.

**Comment by JenySadadia** [comment]
Hi @himanshu007-creator , are you still working on this?
