### ISSUE TITLE
Extend LAVA test coverage with more test plans

### ISSUE THREAD

**Issue by pawiecz** [kernelci/kernelci-api#295]
Baseline tests now cover kunit and verifying kernel version. To make sure the new pipeline can substitute current setup, use case coverage should be extended. This task aims at covering LAVA TestJobs submission use case.

- [x] prepare local API/pipeline environment
- [x] enable `lava-callback` service
- [x] check possible candidates for quickly executed TestJobs with high device availability
- [ ] kernelci/kernelci-core#2130
- [ ] add new KernelCI jobs to the default pipeline configuration

**Comment by gctucker** [comment]
Note: I think we can stick to the current hard-coded limitations for now e.g. only x86 and fixed rootfs URLs etc. when adding new tests.  Then we can gradually add these dynamic parameters one by one.

**Comment by pawiecz** [comment]
[aaeon-UPN-EHLX4RE-A10-0864](https://lava.collabora.dev/scheduler/device_type/aaeon-UPN-EHLX4RE-A10-0864) was chosen as a potential candidate for extending LAVA test coverage.

KernelCI baseline tests [are executed fine](https://staging.lava.collabora.dev/scheduler/job/524334) when using the [same kernel/modules as the healthcheck TestJob](https://lava.collabora.dev/scheduler/job/11470704).

Simple substitution of kernel/modules with KernelCI ones (hosted either on [early access](https://staging.lava.collabora.dev/scheduler/job/524326) or [staging](https://staging.lava.collabora.dev/scheduler/job/524330) storage) does not boot the device under test.

**Comment by pawiecz** [comment]
Just like @gctucker hinted, [minnowboard-turbot-E3826](https://lava.collabora.dev/scheduler/device_type/minnowboard-turbot-E3826) might bring results quicker because they boot on plain defconfig without a need for any additional fragments (see kernelci/kernelci-core#2102).

**Comment by pawiecz** [comment]
> Simple substitution of kernel/modules with KernelCI ones (hosted either on [early access](https://staging.lava.collabora.dev/scheduler/job/524326) or [staging](https://staging.lava.collabora.dev/scheduler/job/524330) storage) does not boot the device under test.

These devices will require adding a config fragment like the one used in their healthcheck job definition: https://gitlab.collabora.com/lava/health-check-kernels/-/blob/linux-5.18/.gitlab-ci.yml#L21-22
