### ISSUE TITLE
Load authentication secret key from environment

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#3]
The current `api.auth` implementation has a hard-coded secret key inside the `Authentication` class.  This was a quick way to get started, but should be replaced with a key provided by the user via the Fast API settings feature:
https://fastapi.tiangolo.com/advanced/settings/

Steps:
- [ ] Set up a local instance following the instructions in the README
- [ ] Create a user and make sure login works
- [ ] Update `api.auth` to read the secret key from the FastAPI settings via the environment
- [ ] Define an environment file in `docker-compose.yaml`
- [ ] Generate a new key with with `openssl rand -hex 32` and store it in the docker-compose environment file
- [ ] Restart docker-compose and check that the user can still login with the new key

Then create the following commits on a branch:

1. Remove hard-coded secret key in `api.auth` and load it from the settings instead
2. Add an environment file to `docker-compose.yaml`:
```yaml
    env_file:
    - .env
```
3. Update README.md with instructions to create the key and store it in the `.env` file

Push this branch to a fork of `kernelci-api` and create a pull request.

**Comment by gctucker** [comment]
OK so it looks like the api container is already running, although the mongod one has stopped.

From the `kernelci-api/docker` directory, could you please try to run `docker-compose down`?  This will stop and remove any running containers.  Then `docker-compose ps` should show an empty list.  Then you can start things again with `docker-compose up --build` and see if it works this time.

By the way, you can use \``` to show unformatted text in comments. See the GitHub Markdown guide for more details: https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by JenySadadia** [comment]
@gctucker , please review the PR on this issue:
https://github.com/kernelci/kernelci-api/pull/6

**Comment by gctucker** [comment]
It's hard to tell what went wrong with your setup, I don't think I've seen this issue before.  Maybe try `docker-compose down`, make sure `docker-compose ps` shows nothing as well as `docker ps` in case some container is running outside of docker-compose,  remove the data directory in `docker/db/data` and then start again.  You shouldn't need to use `sudo`.  If this worked initially then it should work again after starting again from scratch.
