### ISSUE TITLE
User account management

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#304]
While we have some basic implementation to have user accounts with OAuth2 and JWT tokens to access the API, there are still several things that need to be considered in order to make it fully production-ready.

The requirements so far are:
* New public users should be able to sign up like on any free service
* Test data (nodes) sent by users should be owned by them
* Test data is persistent in the database
* All the test data should be publicly readable
* Only the owners of the test data should be able to update it
* The ownership of test data can be shared with other users using groups
* Users should be able to leave groups but not add themselves to groups
* Users with admin rights can create new groups, add users to groups and give admin rights to other users on a per-group basis
* Users should be able to change their passwords themselves as well as all the fields of their user profile
* User data should be managed accordingly to regulations such as GDPR
* Each user should have a test data quota (size used on database storage and / or node count)
* A small amount of non-persistent file storage capacity should be provided for each user account to allow experimentation

Task breakdown:
- [x] #299
- [x] #298
- [x] #300
- [x] #309
- [x] Implement full user management

**Comment by JenySadadia** [comment]
`fastapi-users` has been integrated to implement user management tools.
