### ISSUE TITLE
Add Azure Files as Storage implementation

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#308]
One of the options for storage is Azure Files.  As such, this issue is about adding a Storage implementation in kernelci-core to be able to use it.  There's a Python package available for it and early investigation has shown that it provides all the required features.  It may be used for the Early Access phase as an alternative to the simpler SSH / Nginx approach.  We'll then decide whether to use it in production once other solutions have been considered and compared.

- [x] AzureFiles class implemented
- [x] Tested with `kci storage`
- [x] Summary about how to use it for Early Access

**Comment by gctucker** [comment]
@nuclearcat The checklist is not complete, so I'm reopening this issue.

**Comment by nuclearcat** [comment]
I didn't close it, i guess it was closed automatically because it PR 2027 has "Fixes " in text.

**Comment by gctucker** [comment]
Yes, that's a weakness of the GitHub workflow

**Comment by gctucker** [comment]
The Early Access documentation page explains how to use it: https://kernelci.org/docs/api/early-access/
