### ISSUE TITLE
Update `User` section of `docs/api-details.md` 

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-api#313]
Since the `User` model schema has been changed, update the documentation of https://kernelci.org/docs/api/api-details/#users section accordingly. Also, add documentation for newly added endpoints for getting user profiles, users, and user by ID.

Fixes: https://github.com/kernelci/kernelci-api/issues/352

**Comment by JenySadadia** [comment]
https://github.com/kernelci/kernelci-api/pull/416 and https://github.com/kernelci/kernelci-api/pull/424 fixes the issue.

**Comment by gctucker** [comment]
> #416 and #424 fix the issue.

It's nice to link the PRs with the issue, which can be done with `Fixes:` in the PR description or here under the Development section.  I've found it useful later on when taking a look at the work that has been done and updating the overall roadmap.

**Comment by JenySadadia** [comment]
Linked the PRs. Thanks.
