### ISSUE TITLE
Upgrade to latest `fastapi`

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#321]
As a follow-up from #306, we should consider upgrading to the latest FastAPI (0.101 at the moment) to keep the codebase up-to-date.  This also involves upgrading dependencies such as Pydantic, PyYAML and a few others.

It's not required for Early Access but would be good to have for the initial production deployment as the current FastAPI version [0.68.1](https://pypi.org/project/fastapi/0.68.1/) is from 2 years ago

**Comment by JenySadadia** [comment]
Addressed in https://github.com/kernelci/kernelci-api/pull/554.
