### ISSUE TITLE
KernelCI API Python project packaging

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#327]
The Python package in `kernelci-api` is currently called `api` which is not specific enough.  It could be renamed to `kciapi` for example.  Then we need to add a version, build it with `pyproject.toml` and upload it to PyPI.

**Comment by yurinnick** [comment]
>  upload it to PyPI

I am not sure that PyPi would be an optimal way to distribute the package. Given that API is a service it would make more sense to setup docker image build and publish.

**Comment by gctucker** [comment]
I think we have to distribute the `kernelci` Python package from `kernelci-core` in PyPI so it can be used more widely, we could even have it in Debian at some point.  In fact an older version of `kernelci` was already sent to PyPI.

Then of course we would add it to the dependencies in `kernelci-api` so it will get installed like the other ones in the Docker image etc.

I'm not proposing to distribute the `kernelci-api` code with PyPI, it's a very narrow "application" use-case.

**Comment by gctucker** [comment]
Ah sorry I mixed up this issue with the other discussion topic.  Yes this one should be closed :)

**Comment by gctucker** [comment]
Basically, the idea here was to have a way to share the models, but having the shared models in `kernelci-core` and the `kernelci` Python package makes more sense than having client code depend on `kernelci-api`.
