### ISSUE TITLE
Replace `aioredis` package with `redis>=4.2.0rc1`

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-api#355]
At the moment new API uses `aioredis` package for asynchronous Redis implementation.
The [aioredis](https://github.com/aio-libs-abandoned/aioredis-py) project repository has been archived and now it is a part of [redis-py 4.2.0-rc1](https://github.com/redis/redis-py/releases/tag/v4.2.0rc1) package.
We should consider using `redis` package instead to keep the code up-to-date.

The aioredis [README.md](https://github.com/aio-libs-abandoned/aioredis-py#readme) has the instructions for the upgrade.

**Comment by gctucker** [comment]
Maybe we should first complete the investigation of the Pub/Sub improvements?  If we did decide to stop using Redis then this wouldn't be necessary I guess.

**Comment by JenySadadia** [comment]
Issue covered with PR: https://github.com/kernelci/kernelci-api/pull/417
