### ISSUE TITLE
Allow caching artifacts stored in Azure Files

### ISSUE THREAD

**Issue by pawiecz** [kernelci/kernelci-api#359]
As discussed in kernelci/kernelci-core#2102 ([comment-1721081281](https://github.com/kernelci/kernelci-core/pull/2102#issuecomment-1721081281)), LAVA TestJobs which use artifacts from the new API (hosted in Azure Files) were submitted but failed after first run.

Server returns `HTTP/1.1 400 Condition headers are not supported.`/`x-ms-error-code: ConditionHeadersNotSupported` which seems to be a known issue:
https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/storage-files-condition-headers.md

**Comment by gctucker** [comment]
But this worked :shrug: https://lava.collabora.dev/scheduler/job/11578854

**Comment by pawiecz** [comment]
True - it looks like only the artifacts from `64f529118326c545a780c155` were affected (which I initially tested against):

![Screenshot from 2023-09-21 14-34-11](https://github.com/kernelci/kernelci-api/assets/6019706/4c7dd379-c9b3-49e6-8c48-43023bae8dea)

Closing the issue as it's not manifesting itself anymore.

**Comment by gctucker** [comment]
OK so probably it was a temporary infrastructure error in the LAVA lab or something like that.
