### ISSUE TITLE
Align api.models.Revision with meta-data produced by kernelci-core

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#37]
The `api.models.Revision` model serves the same purpose as the `revision` entry in the build meta-data produced by kernelci-core.  As things currently stand, this is the model from #35:

```python
class Revision(BaseModel):
    tree: str
    branch: str
    commit: str
```
and this is an example of what kernelci-core stores in bmeta.json:
```json
    "revision": {
        "branch": "master",
        "commit": "fa55b7dcdc43c1aa1ba12bca9d2dd4318c2a0dbf",
        "describe": "v5.16-rc1",
        "describe_verbose": "v5.16-rc1",
        "tree": "mainline",
        "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
    }
```

Aligning both things means we could then directly submit a Revision object from the build meta-data, and conversely the meta-data could be recreated when getting a Node.Revision object back from the API.  As outlined in the past, `describe_verbose` seems really superfluous.  It is very useful to have a documented and reproducible way to generate this string, but there's no value of having two versions of `git describe`.  So the code currently creating `describe_verbose` could be kept to populate the `describe` attribute, and the `describe_verbose` attribute could be dropped.

Essentially, this is the current Git command from `kernelci.build.get_describe_verbose()`:
```
git describe --always --match=v[1-9]\*
```
which relies on all the version tags from mainline or stable to have been fetched first.  This provides a unified version of describing the commit in a more human-readable way than the plain SHA1.

Then the `tree` attribute has shown to be very useful, as Git URLs sometimes change or alternative ones may be used to access the same repository.  In summary, this is what the proposed models and meta-data should look like:

```python
class Revision(BaseModel):
    tree: str
    url: str
    branch: str
    commit: str
    describe: str
```

```json
    "revision": {
        "tree": "mainline",
        "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git",
        "branch": "master",
        "commit": "fa55b7dcdc43c1aa1ba12bca9d2dd4318c2a0dbf",
        "describe": "v5.16-rc1"
    }
```

The `Revision` model could of course have some extra validation to check the fields follow the expected format (valid URL etc.).

- [x] #42 
- [ ] ~~kernelci-core bmeta.json update to drop describe_verbose~~  This is not necessary, there's no requirement for full compatibility between the legacy system and the new API.

**Comment by gctucker** [comment]
@spbnick Do you see anything missing from this sample revision meta-data in order to be able to submit it to KCIDB?  I believe `url`, `branch` and `commit` are the only required fields, and the URLs need to be "uniquified" for each tree, but please confirm.

```json
    "revision": {
        "tree": "mainline",
        "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git",
        "branch": "master",
        "commit": "fa55b7dcdc43c1aa1ba12bca9d2dd4318c2a0dbf",
        "describe": "v5.16-rc1"
    }
```

**Comment by JenySadadia** [comment]
Hello @gctucker 

For the second task: `kernelci-core bmeta.json update to drop describe_verbose`
However, I see we have added `Revision.version` field which is containing value of `describe_verbose` using `kernelci.build.git_describe_verbose`.
Do we still need to remove `describe_verbose` from bmeta.json?

**Comment by gctucker** [comment]
Yes the original idea for this issue was to have a single "git describe" string with the formatting used for `describe_verbose` rather than two strings.  However there are cases like for linux-next where keeping the default git describe is more useful.  Also I think this should be reconsidered now that we have the `KernelVersion` model.  See this for example:

https://storage.kernelci.org/next/master/next-20221208/x86_64/x86_64_defconfig/gcc-10/bmeta.json
```json
    "revision": {
        "branch": "master",
        "commit": "f925116b24c0c42dc6d5ab5111c55fd7f74e8dc7",
        "describe": "next-20221208",
        "describe_verbose": "v6.1-rc8-14040-gf925116b24c0",
        "tree": "next",
        "url": "https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git"
    }
```

It's really useful to show the standard git describe `next-20221208` in email reports and web dashboard etc. as it's the most recognisable one for users.  Still having `v6.1-rc8-14040-gf925116b24c0` is also useful as it tells us the kernel version and it's standard across all branches, but now we mostly have that already in the version model.  The only bit that's missing with the new API schema is the number of commits since the kernel tag, e.g. `14040` in the example above.  I don't think that's enough to justify having this separate string though, and when there isn't a special tag on the git branch like the ones on linux-next then the standard describe will show this information anyway.

So I think this issue should be redefined to just setting the plain git describe in the `Revision.describe` for the new API.  Then the bmeta.json stuff will get reworked as the kernelci-core code evolves to run builds with the new pipeline anyway, and I don't think we need to do anything as part of this current issue.  The `describe_verbose` entry will vanish once it's not used anymore as that seems to be what we're heading for.

**Comment by JenySadadia** [comment]
Okay, Thanks for explaining.
By "So I think this issue should be redefined to just setting the plain git describe in the `Revision.describe` for the new API.", do you mean setting value from `kernelci.build.git_describe` method without formatting it with `describe.strip().replace('/', '_')`?

**Comment by gctucker** [comment]
Yes I think we can just use the regular output of `git describe` in the `Revision.describe` field.

**Comment by JenySadadia** [comment]
Okay.
I'll close this issue and we can create a new one for it.

**Comment by gctucker** [comment]
Erm I actually think it's better to just rework the definition of what has to be done in this one as the intention is the same.  That way we keep track of the history and the logic that led to this choice.

**Comment by JenySadadia** [comment]
It is the same as creating a new one and mentioning this issue there. 
Anyway, updating this one is also fine.
