### ISSUE TITLE
Remove `/hash` endpoint

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#386]
The `/hash` endpoint was initially required in order to create new user entries.  We now have `api.admin` to create an admin user directly in the Mongo database, which can then be used to create new users.  The `/hash` endpoint causes some potential security issue as it facilitates brute-force password attacks.  Hashed passwords rely on the internal secret key which is specific to each API instance.

- [ ] `/hash` endpoint removed from `api.main`
- [ ] unit tests updated accordingly
- [ ] end-to-end tests updated accordingly

**Comment by JenySadadia** [comment]
I have already moved it in the `fastapi-users` integration [PR](https://github.com/kernelci/kernelci-api/pull/377).

**Comment by gctucker** [comment]
OK then please link the PR to this issue with `Fixes:`.
