### ISSUE TITLE
User email field is missing unique index

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#401]
With the new user management implementation based on `fastapi-users`, there doesn't appear to be any constraint for the user email addresses to be unique.  I've been able to create several users with the same email, then when doing things like a password reset which takes the email address as input a random user that had a matching email address was selected in the database.

**Comment by gctucker** [comment]
I see there's some code to prevent updating a user entry with an email address that already exists:
```python
    async def _update(self, user: models.UP, update_dict: Dict[str, Any]) -> models.UP:
        validated_update_dict = {}
        for field, value in update_dict.items():
            if field == "email" and value != user.email:
                try:
                    await self.get_by_email(value)
                    raise exceptions.UserAlreadyExists()
                except exceptions.UserNotExists:
                    validated_update_dict["email"] = value
                    validated_update_dict["is_verified"] = False
            elif field == "password" and value is not None:
                await self.validate_password(value, user)
                validated_update_dict["hashed_password"] = self.password_helper.hash(
                    value
                )
            else:
                validated_update_dict[field] = value
        return await self.user_db.update(user, validated_update_dict)
```
However that's not inforced when directly inserting a new admin into the database.  So probably we should still also have an index to ensure this field is unique like the username.

**Comment by JenySadadia** [comment]
We are extending `BeanieBaseUser` model for defining the `User` model.
The base model already has a unique index on `email` field.
```
class BeanieBaseUser(BaseModel):
    email: str
    hashed_password: str
    is_active: bool = True
    is_superuser: bool = False
    is_verified: bool = False

    class Settings:
        email_collation = Collation("en", strength=2)
        indexes = [
            IndexModel("email", unique=True),
            IndexModel(
                "email", name="case_insensitive_email_index", collation=email_collation
            ),
        ]
```

**Comment by JenySadadia** [comment]
When we try to add a user with existing email address the API returns `REGISTER_USER_ALREADY_EXISTS` error:
```
$ curl -X 'POST'   'http://localhost:8001/latest/user/register'   -H 'accept: application/json'   -H 'Content-Type: application/json'  -H 'Authorization: Bearer TOKEN' -d '{
  "email": "test@gmail.com",
  "password": "test12345",
  "username": "jeny"
}'
{"detail":"REGISTER_USER_ALREADY_EXISTS"}
```

**Comment by JenySadadia** [comment]
Somehow parent class `BeanieBaseUser` is not creating unique index on `email` field. It allows multiple users with the same email while inserting users directly with `db.create`.
Added a commit to https://github.com/kernelci/kernelci-api/pull/412 to fix this.

**Comment by gctucker** [comment]
I think the real fix would be to have the indexes when the database is initialised for the first time, and that shouldn't be part of the script that's used to create the first admin user.  I guess we're lucky and it'll work for now as you can't do anything without an admin user in practice, but it's not the right place for this fix.  It seems more like a workaround.

Probably we should revisit this again once all the changes related to user management have landed.

**Comment by JenySadadia** [comment]
Nope, I didn't add the fix in the script for creating admin user. I fixed indexes in `api.user_models` in the `User` model itself. Please see https://github.com/kernelci/kernelci-api/pull/412/commits/dc6d8966d83083dfb691bb4636c97dcaedcbc92f
When the API will run, it will automatically create an index in the database.

**Comment by gctucker** [comment]
Ah yes sorry, I misread #412 which makes changes both in the models and in the admin setup script.
