### ISSUE TITLE
Secret key shouldn't be randomly generated in tests

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#402]
The tests run on GitHub currently have a secret key for the test instance generated randomly on the fly.  This is not best practice for automated tests as it means each run will be with a different key, which might lead to corner-case problems that can't be reproducible.  Instead, the key should just be hard-coded with a comment explaining how it was generated.

**Comment by JenySadadia** [comment]
Yes, I agree. We should have all the settings for tests hard-coded.
