### ISSUE TITLE
Query attributes don't handle boolean values

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#410]
When searching for some database entries, the boolean values don't seem to be converted to booleans but remain strings.  For example, these two commands don't return any result whereas every user entry in the database has an `is_active` field set to `true` or `false`:
```
kci user find is_active=true
kci user find is_active=false
```

**Comment by JenySadadia** [comment]
This can be the sub-issue of https://github.com/kernelci/kernelci-api/issues/390
