### ISSUE TITLE
Updating the current user's username fails unless superuser

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-api#411]
When trying to update the username of my current user I get a `Forbidden` HTTP 403 error:
```
$ ./kci user whoami --api=local
{
   "id": "654e821d1710db5090716e97",
   "email": "guillaume.tucker@gmail.com",
   "is_active": true,
   "is_superuser": false,
   "is_verified": true,
   "username": "test003",
   "groups": []
}
$ ./kci user update --api=local --new-username=gtucker
Error: 403 Client Error: Forbidden for url: http://172.17.0.1:8001/latest/user/654e821d1710db5090716e97
Forbidden
```
This worked with a superuser account and `--username=test003` so it's most likely a small bug on the API side around permission checks.

**Comment by JenySadadia** [comment]
Tested with https://github.com/kernelci/kernelci-core/pull/2184. Below commands works:

Update current user:
```
$ ./kci user update username=test123 email=test123@gmail.com
```
Update another user:
```
$ ./kci user update --username=test username=test123
```

**Comment by gctucker** [comment]
OK thanks maybe there was a temporary bug or issue in my settings.  I'll double check that with the latest code.

**Comment by gctucker** [comment]
Confirmed this is working now, probably it was a glitch at some point.
