### ISSUE TITLE
Enable pylint on all the files under `api/`

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-api#426]
At the moment, `pylint` is running on most of the source files under `api/` directory in the Github workflow.
Enable it on all the remaining files to make sure that developers and maintainers follow expected coding standards.

- [ ] Check and fix pylint errors for all the source files under `api/` directory
- [ ] Update job to run pylint in the workflow file `main.yml`
- [ ] Test with Github Actions

**Comment by gctucker** [comment]
Yes I think `api.client` can be deleted, I doubt it's still working anyway.  We should just provide some sample ways to use the raw API in the documentation as it shouldn't depend on the `kci` command line tool - the dependency goes the other way.  In fact the generated documentation probably already does that so maybe we can just delete that file, then we'll be able to run pylint on all the API files.

**Comment by JenySadadia** [comment]
Okay. Thanks.
