### ISSUE TITLE
pymongo.errors.DuplicateKeyError on api startup

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-api#444]
We are getting some errors during API startup, but instance keep working

today at 12:13:42 PM pymongo.errors.DuplicateKeyError: Index build failed: c9638a51-a75c-4c47-9494-6c89a5c86c46: Collection kernelci.user ( 2e3104d0-d86d-4d4a-9b3a-97d8c3c14d16 ) :: caused by :: E11000 duplicate key error collection: kernelci.user index: email_1 dup key: { email: "kernelci-tsc@groups.io" }, full error: {'ok': 0.0, 'errmsg': 'Index build failed: c9638a51-a75c-4c47-9494-6c89a5c86c46: Collection kernelci.user ( 2e3104d0-d86d-4d4a-9b3a-97d8c3c14d16 ) :: caused by :: E11000 duplicate key error collection: kernelci.user index: email_1 dup key: { email: "kernelci-tsc@groups.io" }', 'code': 11000, 'codeName': 'DuplicateKey', 'keyPattern': {'email': 1}, 'keyValue': {'email': 'kernelci-tsc@groups.io'}}

**Comment by JenySadadia** [comment]
This is expected behavior as staging has 2 users with the same email.
```
$ ./kci user find email=kernelci-tsc@groups.io
[{"id": "62058f7a91aebf7ab63f1492", "email": "kernelci-tsc@groups.io", "is_active": true, "is_superuser": false, "is_verified": false, "username": "staging.kernelci.org", "groups": []}, {"id": "62f3ec222d0a223569d55be7", "email": "kernelci-tsc@groups.io", "is_active": true, "is_superuser": true, "is_verified": true, "username": "admin", "groups": [{"id": "649190b01432ccfdb575a250", "name": "admin"}]}]
```

It's weird as API should not allow adding users with the same email. Seems like a bug in `setup_admin_user` script. I'll take a look.
