### ISSUE TITLE
We need to install templates under api module directory, not in modules root

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-api#482]
Because of this we are forced to call twice: 
https://github.com/kernelci/kernelci-api/pull/458/commits/70bc3cf83e8087bafae03c5438dac839117bf15e#diff-c2c3b0c64a2690193a471cfc8068fcb622a23e1b4323c693b6ba20835f26fb88R724
mod_root = os.path.dirname(mod_root)

Reason is because file path is:
```
/usr/local/lib/python3.10/site-packages/templates/viewer.html
```
While should be:
```
/usr/local/lib/python3.10/site-packages/api/templates/viewer.html
```

**Comment by JenySadadia** [comment]
`api` is structured to just have source files atm. Everything else is organized in multiple directories.

Template loader in user manager looks like below:
```
self._template_env = jinja2.Environment(
            loader=jinja2.FileSystemLoader("./templates/")
        )
```

Can you do something like that in the viewer as changing the location would break other functionalities?
Also, we can consider changing API directory structure in the next milestone and have a discussion on it if required.

**Comment by nuclearcat** [comment]
did you check if email templates still works? i might just follow example how they are implemented

**Comment by JenySadadia** [comment]
Yes, they are being used in user verification and password reset operations.
Did you find any issues with them?

**Comment by nuclearcat** [comment]
After pyproject.toml changes their location has been changed, so i think it will be good idea to recheck if everything still works.

**Comment by JenySadadia** [comment]
It turns out that templates were not accessible when API service runs using python package.
Some adjustments were needed in the `pyproject.toml` and `api/user_manager.py` to access templates.

**Comment by JenySadadia** [comment]
See https://github.com/kernelci/kernelci-api/pull/486
