### ISSUE TITLE
migration scripts are not included in package

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-api#513]
I am not sure it is good idea to include them with package, but just as we are doing migration sometimes, we need to document somehow procedure how we will do that, plus if possible to automate migrations to certain extent, including backup, maybe fetching migration scripts, running them, verifying results, rolling back on failure.

**Comment by JenySadadia** [comment]
I'll take a look if I can include the migration scripts to the package with dev mode.
About the documentation, an initial version is here: https://github.com/kernelci/kernelci-api/blob/main/doc/api-details.md#migrations
It can be enhanced though.
