### ISSUE TITLE
Add test for api.pubsub.PubSub.subscribe method

### ISSUE THREAD

**Issue by mgalka** [kernelci/kernelci-api#71]
This issue is about adding a test case for the `subscribe` method from `api.pubsub.PubSub` module.

It needs investigation if [fakeredis](https://pypi.org/project/fakeredis/) is suitable for our needs.
Due to its documentation it supports `aioredis`

> You can also use fakeredis to mock out aioredis. This is a much newer addition to fakeredis (added in 1.4.0) with less testing, so your mileage may vary. Both version 1 and version 2 (which have very different APIs) are supported. The API provided by fakeredis depends on the version of aioredis that is installed.

**Comment by gctucker** [comment]
Maybe this is something @JenySadadia could pick up while @alexandrasp is still working on #70.

**Comment by JenySadadia** [comment]
@mgalka has already fixed this by https://github.com/kernelci/kernelci-api/pull/89.
